postgres_conn:
  schema_name: "credit_risk"
  table_name: "credit_risk_staging"
  feature_store_path: "Artifacts"
  feature_store_folder_name: "feature_store"
  feature_store_file_name: "feature_store.csv"