postgres_conn:
  dbname: "postgres"
  user: "postgres"
  password: "1994"
  host: "localhost"
  port: "5432"
  schema_name: "credit_risk"
  table_name: "credit_risk_staging"
  feature_store_path: "Artifacts"
  feature_store_folder_name: "feature_store"
  feature_store_file_name: "feature_store.csv"